// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkeAlasr4auU4gNGZgW2umvCF4MWvvtZk',
    appId: '1:860581243175:web:856125015827effdc2a102',
    messagingSenderId: '860581243175',
    projectId: 'catering-services-app',
    authDomain: 'catering-services-app.firebaseapp.com',
    storageBucket: 'catering-services-app.appspot.com',
    measurementId: 'G-WJ8ZQPW5CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5OQNtFsL7Ys1a5fKim0O2eyDrtJ0qZYU',
    appId: '1:860581243175:android:e2c2c0e067e135c9c2a102',
    messagingSenderId: '860581243175',
    projectId: 'catering-services-app',
    storageBucket: 'catering-services-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEJWh5gV_d8V9lbMcZu6xHdiEN4evEmPs',
    appId: '1:860581243175:ios:30eb15a8465bfe17c2a102',
    messagingSenderId: '860581243175',
    projectId: 'catering-services-app',
    storageBucket: 'catering-services-app.appspot.com',
    iosBundleId: 'com.example.cateringServiceManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEJWh5gV_d8V9lbMcZu6xHdiEN4evEmPs',
    appId: '1:860581243175:ios:30eb15a8465bfe17c2a102',
    messagingSenderId: '860581243175',
    projectId: 'catering-services-app',
    storageBucket: 'catering-services-app.appspot.com',
    iosBundleId: 'com.example.cateringServiceManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkeAlasr4auU4gNGZgW2umvCF4MWvvtZk',
    appId: '1:860581243175:web:035bc560fdba3ad1c2a102',
    messagingSenderId: '860581243175',
    projectId: 'catering-services-app',
    authDomain: 'catering-services-app.firebaseapp.com',
    storageBucket: 'catering-services-app.appspot.com',
    measurementId: 'G-RM3S650GG9',
  );
}
